AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Open News Insights - News article processing pipeline

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: python3.11
    Environment:
      Variables:
        LOG_LEVEL: INFO
    Tracing: Active

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment
  
  LogRetentionDays:
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Description: CloudWatch log retention period in days
  
  ExternalApiUrl:
    Type: String
    Default: ""
    Description: External API URL for result forwarding (optional)
  
  ExternalApiKey:
    Type: String
    Default: ""
    NoEcho: true
    Description: External API authentication key (optional)

Resources:
  # IAM Role for Lambda Function
  OpenNewsInsightsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "OpenNewsInsightsRole-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: 
                  - !Sub "arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0"
        - PolicyName: ComprehendAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - comprehend:DetectSentiment
                  - comprehend:DetectPiiEntities
                  - comprehend:DetectKeyPhrases
                  - comprehend:DetectDominantLanguage
                Resource: '*'
        - PolicyName: CloudWatchLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/open-news-insights-${Environment}*"

  # CloudWatch Log Group
  OpenNewsInsightsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/open-news-insights-${Environment}"
      RetentionInDays: !Ref LogRetentionDays

  # Lambda Function
  OpenNewsInsightsFunction:
    Type: AWS::Serverless::Function
    DependsOn: OpenNewsInsightsLogGroup
    Properties:
      FunctionName: !Sub "open-news-insights-${Environment}"
      CodeUri: src/
      Handler: handler.lambda_handler
      Description: Process news articles with optional AI enrichment
      Role: !GetAtt OpenNewsInsightsRole.Arn
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          EXTERNAL_API_URL: !Ref ExternalApiUrl
          EXTERNAL_API_KEY: !Ref ExternalApiKey
          AWS_REGION: !Ref AWS::Region
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /process
            Method: post
            RestApiId: !Ref OpenNewsInsightsApi
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt OpenNewsInsightsDeadLetterQueue.Arn

  # Dead Letter Queue for failed Lambda invocations
  OpenNewsInsightsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "open-news-insights-dlq-${Environment}"
      MessageRetentionPeriod: 1209600  # 14 days
      VisibilityTimeoutSeconds: 60

  # API Gateway
  OpenNewsInsightsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "open-news-insights-api-${Environment}"
      StageName: !Ref Environment
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: >
          {
            "requestId": "$context.requestId",
            "requestTime": "$context.requestTime",
            "httpMethod": "$context.httpMethod",
            "path": "$context.path",
            "status": "$context.status",
            "responseLength": "$context.responseLength",
            "responseTime": "$context.responseTime",
            "userAgent": "$context.identity.userAgent",
            "sourceIp": "$context.identity.sourceIp"
          }
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'Content-Type, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      DefinitionBody:
        openapi: 3.0.1
        info:
          title: Open News Insights API
          version: 1.0.0
          description: API for processing news articles with optional AI enrichment
        paths:
          /process:
            post:
              summary: Process news article
              description: Fetch, extract, and optionally enrich news article content
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      required:
                        - url
                      properties:
                        url:
                          type: string
                          format: uri
                          description: News article URL to process
                          example: "https://www.theguardian.com/world/2024/jan/01/example-article"
                        features:
                          type: object
                          description: Feature flags to control processing steps
                          properties:
                            llm_normalization:
                              type: boolean
                              default: false
                              description: Enable AWS Bedrock text normalization
                            sentiment_analysis:
                              type: boolean
                              default: false
                              description: Enable sentiment analysis via AWS Comprehend
                            pii_detection:
                              type: boolean
                              default: false
                              description: Enable PII detection via AWS Comprehend
                            topic_extraction:
                              type: boolean
                              default: false
                              description: Enable topic and key phrase extraction
                            summarization:
                              type: boolean
                              default: false
                              description: Enable text summarization via AWS Bedrock
                            external_api_forwarding:
                              type: boolean
                              default: false
                              description: Forward results to external API
              responses:
                '200':
                  description: Successful processing
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          success:
                            type: boolean
                          data:
                            type: object
                          processing_metadata:
                            type: object
                '400':
                  description: Bad request - invalid input parameters
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          success:
                            type: boolean
                            example: false
                          error:
                            type: object
                            properties:
                              type:
                                type: string
                              message:
                                type: string
                              step:
                                type: string
                '500':
                  description: Internal server error
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          success:
                            type: boolean
                            example: false
                          error:
                            type: object
            options:
              summary: CORS preflight
              responses:
                '200':
                  description: CORS headers
                  headers:
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Headers:
                      schema:
                        type: string

  # CloudWatch Log Group for API Gateway
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/open-news-insights-${Environment}"
      RetentionInDays: !Ref LogRetentionDays

  # CloudWatch Alarms
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "OpenNewsInsights-${Environment}-LambdaErrors"
      AlarmDescription: "Lambda function error rate is too high"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref OpenNewsInsightsFunction
      TreatMissingData: notBreaching

  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "OpenNewsInsights-${Environment}-LambdaDuration"
      AlarmDescription: "Lambda function duration is too high"
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 240000  # 4 minutes (80% of 5 minute timeout)
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref OpenNewsInsightsFunction
      TreatMissingData: notBreaching

Outputs:
  OpenNewsInsightsApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${OpenNewsInsightsApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"
    Export:
      Name: !Sub "${AWS::StackName}-ApiUrl"

  OpenNewsInsightsFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt OpenNewsInsightsFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"

  OpenNewsInsightsFunctionName:
    Description: Lambda Function Name
    Value: !Ref OpenNewsInsightsFunction
    Export:
      Name: !Sub "${AWS::StackName}-FunctionName"

  OpenNewsInsightsRoleArn:
    Description: IAM Role ARN for Lambda Function
    Value: !GetAtt OpenNewsInsightsRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"

  OpenNewsInsightsLogGroup:
    Description: CloudWatch Log Group for Lambda Function
    Value: !Ref OpenNewsInsightsLogGroup
    Export:
      Name: !Sub "${AWS::StackName}-LogGroup"

  OpenNewsInsightsDeadLetterQueueUrl:
    Description: Dead Letter Queue URL
    Value: !Ref OpenNewsInsightsDeadLetterQueue
    Export:
      Name: !Sub "${AWS::StackName}-DLQUrl"